image: ubuntu:jammy

stages:
  - build
    
clang-format:
  stage: build
  before_script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y software-properties-common wget cmake git findutils clang-format-14
  script:
    - ln -s `which clang-format-14` clang-format && PATH=$PATH:$PWD ./scripts/clang-format-test.sh
 
# performing the static analysis code check using a custom docker image with the llvm installation we need
code_checks:
  stage: build
  before_script:
    - apt update -y && apt-get upgrade -y
    - apt install -y software-properties-common wget clang-14 libclang-14-dev clang-tidy-14 python3 python-is-python3 cmake
  script:
    - mkdir build && cd build
    - CXX=clang++-14 cmake .. -DVECGEOM_BUILTIN_VECCORE=ON -DVECGEOM_ROOT=OFF -DVECGEOM_GDML=OFF -DVECGEOM_TEST_STATIC_ANALYSIS=ON -DVECGEOM_BACKEND=Scalar
    - make -j8
    - ctest -j8 -V
     
# normal build against a recent ROOT; using the ALICE software stack
# because it comes fully consistent on cvmfs (including compiler etc)
with_ROOT:
   tags:
     - cvmfs
   image: cern/cc7-base
   stage: build
   before_script:
     - yum install environment-modules -y
     - yum install -y unzip autoconf automake make gcc
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv CMake::v3.18.2-1)"
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv ROOT::v6-18-04-8)"
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv Vc::1.4.1-6)"
   script:
     - mkdir build && cd build
     - cmake .. -DVECGEOM_BUILTIN_VECCORE=ON -DVECGEOM_BACKEND=Vc -DVc_DIR=${VC_ROOT}/lib/cmake -DVECGEOM_ROOT=ON -DVECGEOM_GDML=OFF
       # for the moment exclude the E03 test since downloading E03 root geometry has problems on the CI machine
     - make -j8 VERBOSE=ON && ctest --output-on-failure -j8 -E E03

# build for USING_NAVINDEX=ON (using the cvmfs ALICE software stack: TODO: convert to project/sft...)
with_NAVINDEX:
   tags:
     - cvmfs
   image: cern/cc7-base
   stage: build
   before_script:
     - yum install environment-modules -y
     - yum install -y unzip autoconf automake make gcc
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv CMake::v3.18.2-1)"
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv ROOT::v6-18-04-8)"
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv Vc::1.4.1-6)"
   script:
     - mkdir build && cd build
     - cmake .. -DVECGEOM_BUILTIN_VECCORE=ON -DVECGEOM_BACKEND=Vc -DVc_DIR=${VC_ROOT}/lib/cmake -DVECGEOM_USE_NAVINDEX=ON -DVECGEOM_ROOT=ON -DVECGEOM_GDML=OFF
       # for the moment exclude the E03 test since downloading E03 root geometry has problems on the CI machine
     - make -j8 VERBOSE=ON && ctest --output-on-failure -j8 -E E03
