#!/bin/bash -x
THIS=$(dirname $0)
echo source $THIS/jk-setup.sh $LABEL $COMPILER $BUILDTYPE $EXTERNALS $BACKEND > setup.sh
source $THIS/jk-setup.sh $LABEL $COMPILER $BUILDTYPE $EXTERNALS $BACKEND

echo "Dumping the full environment ---------------------------------------------------------"
env | sort | sed 's/:/:?     /g' | tr '?' '\n'
echo "--------------------------------------------------------------------------------------"

#---Run the CTest script depending on the compiler------------------------------------------
ctest -VV -S ${THIS}/vecgeom-ctest.cmake,Nightly
status=$?

exit $status
